/* cliche_swaps.browser.js — hand-curated, meaning/ROLE-preserving substitutes for the
 * AI-cliché blocklist. TIER 0 of Humanize: swap only the cliché word, keep the sentence.
 * EVERY substitute is corpus-validated: it must not lean AI (full AI corpus + the
 * AI-overused-40 list) — naive "specific" words like quiet/salt/porch are MODERN AI slop
 * and were auto-rejected. Verb entries may split {obj, noobj}: a word's true synonym is
 * its ROLE ("echoes your name" = tells/spells/shouts; bare "echo" = rings).
 * Pure data — no network, no storage, nothing fetched. */
(function () {
  "use strict";
  globalThis.CLICHE_SWAPS = {
    abyss: ["chasm", "trench", "ravine"],
    amber: ["copper", "honey", "russet"],
    angels: ["saints", "guardians"],
    ashes: ["cinders", "soot"],
    beneath: ["under", "below"],
    bones: ["marrow", "ribs", "joints"],
    broken: ["busted", "snapped", "wrecked"],
    burning: ["boiling", "scalding", "blistering"],
    cascade: ["torrent", "downpour", "spill"],
    cascading: ["spilling", "tumbling"],
    celestial: ["orbital", "planetary", "lunar"],
    chains: ["shackles", "handcuffs", "padlocks"],
    concrete: ["pavement", "asphalt", "sidewalk"],
    cosmic: ["galactic", "planetary", "orbital"],
    crimson: ["scarlet", "ruby", "cherry"],
    crystal: ["quartz"],
    demon: ["devil", "tormentor"],
    demons: ["devils", "vices", "habits"],
    diamond: ["jewel", "gemstone"],
    distant: ["faraway", "remote"],
    dreams: ["plans", "wishes", "tickets"],
    drowning: ["sinking", "gasping"],
    dust: ["grit", "powder", "sand", "gravel"],
    echo: ["rebound", "repeat"],
    echoes: ["rebounds", "repeats"],
    echoing: ["repeating", "ringing"],
    electric: ["wired", "voltaic"],
    ember: ["cinder", "coal"],
    embers: ["cinders", "coals"],
    empty: ["vacant", "blank", "cleared"],
    endless: ["ceaseless", "constant", "nonstop"],
    eternal: ["lifelong", "permanent"],
    eternity: ["forever", "lifetimes", "centuries"],
    ethereal: ["airy"],
    faded: ["bleached", "washed"],
    fading: ["dimming", "thinning", "bleaching"],
    fire: ["blaze", "furnace", "bonfire", "gasoline"],
    flame: ["torch"],
    flames: ["sparks", "torches"],
    flicker: ["sputter", "blink"],
    flickering: ["sputtering"],
    forgotten: ["misplaced", "overlooked"],
    fragile: ["brittle", "flimsy"],
    fragments: ["scraps", "splinters"],
    frozen: ["icy", "stiff", "snowbound", "numb"],
    ghost: ["trace", "imprint", "specter"],
    ghosts: ["traces", "imprints", "specters"],
    glimmer: ["glint", "shine"],
    golden: ["gilded", "brassy", "mustard"],
    hands: ["palms", "fingers", "knuckles"],
    heartbeat: ["drumbeat", "metronome"],
    hollow: ["vacant"],
    horizon: ["coastline", "treeline"],
    horizons: ["coastlines", "treelines"],
    infinity: ["forever", "infinitude"],
    kaleidoscope: ["pinwheel", "mosaic"],
    kiss: ["peck", "smooch"],
    labyrinth: ["maze", "warren"],
    light: ["beam", "headlights", "daylight"],
    lightning: ["voltage", "flash"],
    lights: ["lamps", "beams"],
    lonely: ["solo", "friendless"],
    lost: ["stranded", "adrift", "mislaid", "sideways"],
    love: ["affection", "longing", "craving"],
    luminous: ["lamplit"],
    memories: ["keepsakes", "snapshots"],
    memory: ["keepsake", "snapshot"],
    midnight: ["nightfall", "curfew"],
    mist: ["fog", "drizzle", "exhaust"],
    moonlight: ["lamplight", "porchlight", "headlights"],
    neon: ["halogen", "sodium"],
    night: ["evening", "dusk"],
    paradise: ["eden", "utopia"],
    phantom: ["mirage", "specter"],
    phoenix: ["comeback", "rebirth"],
    radiant: ["beaming", "sunlit"],
    restless: ["fidgety"],
    rising: ["climbing", "swelling"],
    road: ["highway", "gravel"],
    roads: ["highways", "backroads"],
    scar: ["welt", "bruise"],
    scars: ["welts", "bruises", "stitches"],
    serenade: ["ballad"],
    shadow: ["outline"],
    shadowed: ["shaded", "dimmed"],
    shadows: ["doorways", "alleys", "corners", "background"],
    shattered: ["smashed", "splintered"],
    shimmer: ["glint", "sheen"],
    silence: ["vacuum"],
    silent: ["hushed", "soundless"],
    silhouette: ["outline", "profile"],
    silhouettes: ["outlines", "profiles"],
    silver: ["pewter"],
    sky: ["clouds", "stratosphere"],
    skyline: ["rooftops", "treeline"],
    soul: ["core", "marrow", "gut", "spine"],
    souls: ["spirits", "bodies"],
    stardust: ["glitter", "confetti"],
    starlight: ["satellites", "lamplight"],
    storm: ["downpour", "squall"],
    stranger: ["drifter", "outsider"],
    streetlight: ["lamppost", "porchlight"],
    streetlights: ["lampposts", "porchlights"],
    streets: ["avenues", "sidewalks", "blocks"],
    surrender: ["yielding", "retreat"],
    symphony: ["overture"],
    tapestry: ["quilt", "patchwork"],
    tears: ["sobs", "weeping", "crying"],
    tender: ["careful"],
    thunder: ["rumble", "growl"],
    unbreakable: ["shatterproof", "ironclad"],
    veins: ["arteries", "bloodstream"],
    velvet: ["satin", "suede"],
    voice: ["tone"],
    void: ["vacuum", "chasm"],
    whisper: ["mutter", "mumble"],
    whispered: ["muttered", "mumbled"],
    whispering: ["muttering", "mumbling"],
    whispers: ["mutters", "mumbles"],
    wildfire: ["brushfire", "bonfire"],
  };
  globalThis.CLICHE_SWAPS_VERB = {
    echo: { obj: ["repeat", "spell", "tell"], noobj: ["ring", "rebound"] },
    echoes: { obj: ["repeats", "spells", "tells", "shouts", "owns", "haunts"], noobj: ["rings", "rebounds"] },
    echoing: { obj: ["repeating", "carrying", "spelling"], noobj: ["ringing", "rebounding"] },
    flicker: ["sputter", "blink"],
    flickering: ["sputtering"],
    glimmer: ["glint"],
    kiss: ["peck"],
    love: ["adore", "cherish", "choose"],
    scar: ["mark"],
    shimmer: ["glint"],
    surrender: ["yield"],
    whisper: { obj: ["mutter", "offer", "breathe", "slip"], noobj: ["mutter", "mumble"] },
    whispered: ["muttered", "mumbled"],
    whispering: ["muttering", "mumbling"],
    whispers: { obj: ["mutters", "offers"], noobj: ["mutters", "mumbles"] },
  };
})();
