/* cliche_swaps.browser.js — hand-curated, meaning-preserving substitutes for the 125
 * AI-cliché blocklist words. TIER 0 of Humanize: when a line is the user's own (reads
 * human) but carries a cliché word, swap ONLY the word and keep their sentence.
 * Curated by hand at build time (the oracle test showed substitute quality is everything:
 * on-device embeddings pick "anyone", a human picks "vacuum"). Substitutes are single
 * tokens, off-blocklist, and chosen to dodge the whole slop FAMILY (silence->hush, not
 * silence->stillness). Ordered best-first; runtime prefers the closest syllable count.
 * Pure data — no network, no storage, nothing fetched. */
(function () {
  "use strict";
  globalThis.CLICHE_SWAPS = {
    abyss: ["chasm", "trench", "ravine"],
    amber: ["copper", "honey", "russet"],
    angels: ["saints", "guardians"],
    ashes: ["cinders", "soot"],
    beneath: ["under", "below", "underneath"],
    bones: ["marrow", "ribs", "joints"],
    broken: ["busted", "cracked", "snapped"],
    burning: ["boiling", "scalding", "blistering"],
    cascade: ["torrent", "downpour", "spill"],
    cascading: ["spilling", "tumbling"],
    celestial: ["orbital", "planetary", "lunar"],
    chains: ["shackles", "handcuffs", "padlocks"],
    concrete: ["pavement", "asphalt", "sidewalk"],
    cosmic: ["galactic", "planetary", "orbital"],
    crimson: ["scarlet", "ruby", "cherry"],
    crystal: ["quartz", "glass"],
    demon: ["devil", "tormentor"],
    demons: ["devils", "vices"],
    diamond: ["jewel", "gemstone"],
    distant: ["faraway", "remote"],
    dreams: ["plans", "wishes"],
    drowning: ["sinking", "gasping"],
    dust: ["grit", "powder", "sand"],
    echo: ["rebound", "reverb", "repeat"],
    echoes: ["rebounds", "reverbs", "repeats"],
    echoing: ["repeating", "ringing"],
    electric: ["wired", "buzzing", "voltaic"],
    ember: ["cinder", "coal"],
    embers: ["cinders", "coals"],
    empty: ["vacant", "bare"],
    endless: ["ceaseless", "constant", "nonstop"],
    eternal: ["lifelong", "permanent"],
    eternity: ["forever", "lifetimes"],
    ethereal: ["weightless", "airy"],
    faded: ["bleached", "washed"],
    fading: ["dimming", "thinning", "bleaching"],
    fire: ["blaze", "furnace", "bonfire"],
    flame: ["torch", "candle"],
    flames: ["sparks", "torches"],
    flicker: ["sputter", "blink"],
    flickering: ["sputtering", "blinking"],
    forgotten: ["misplaced", "overlooked"],
    fragile: ["brittle", "flimsy"],
    fragments: ["scraps", "splinters"],
    frozen: ["icy", "stiff", "snowbound"],
    ghost: ["trace", "imprint", "specter"],
    ghosts: ["traces", "imprints", "specters"],
    glimmer: ["glint", "shine"],
    golden: ["gilded", "yellow", "brassy"],
    hands: ["palms", "fingers", "knuckles"],
    heartbeat: ["pulse", "drumbeat"],
    hollow: ["vacant", "carved"],
    horizon: ["coastline", "treeline"],
    horizons: ["coastlines", "treelines"],
    infinity: ["forever", "infinitude"],
    kaleidoscope: ["pinwheel", "mosaic"],
    kiss: ["peck", "smooch"],
    labyrinth: ["maze", "warren"],
    light: ["beam", "lamp"],
    lightning: ["voltage", "flash"],
    lights: ["lamps", "beams"],
    lonely: ["solo", "friendless"],
    lost: ["stranded", "adrift", "mislaid"],
    love: ["devotion", "affection"],
    luminous: ["glowing", "lamplit"],
    memories: ["keepsakes", "snapshots"],
    memory: ["keepsake", "snapshot"],
    midnight: ["nightfall", "curfew"],
    mist: ["fog", "drizzle"],
    moonlight: ["lamplight", "porchlight"],
    neon: ["halogen", "fluorescent", "sodium"],
    night: ["evening", "dusk"],
    paradise: ["eden", "utopia"],
    phantom: ["mirage", "specter"],
    phoenix: ["comeback", "rebirth"],
    radiant: ["beaming", "sunlit"],
    restless: ["fidgety", "sleepless"],
    rising: ["climbing", "swelling"],
    road: ["highway", "gravel"],
    roads: ["highways", "backroads"],
    sacred: ["holy", "blessed"],
    scar: ["welt", "bruise"],
    scars: ["welts", "bruises"],
    serenade: ["lullaby", "ballad"],
    shadow: ["outline", "shade"],
    shadowed: ["shaded", "dimmed"],
    shadows: ["background", "doorways", "alleys"],
    shattered: ["smashed", "splintered"],
    shimmer: ["glint", "sheen"],
    silence: ["hush", "quiet", "vacuum"],
    silent: ["hushed", "soundless"],
    silhouette: ["outline", "profile"],
    silhouettes: ["outlines", "profiles"],
    silver: ["chrome", "pewter", "tin"],
    sky: ["clouds", "stratosphere"],
    skyline: ["rooftops", "treeline"],
    song: ["tune", "anthem"],
    soul: ["core", "marrow"],
    souls: ["spirits", "bodies"],
    stardust: ["glitter", "confetti"],
    starlight: ["satellites", "lamplight"],
    storm: ["downpour", "squall"],
    stranger: ["drifter", "outsider"],
    streetlight: ["lamppost", "porchlight"],
    streetlights: ["lampposts", "porchlights"],
    streets: ["avenues", "sidewalks"],
    surrender: ["yielding", "retreat"],
    symphony: ["orchestra", "overture"],
    tapestry: ["quilt", "patchwork"],
    tears: ["sobs", "weeping"],
    tender: ["gentle", "careful"],
    thunder: ["rumble", "growl"],
    unbreakable: ["shatterproof", "ironclad"],
    veins: ["arteries", "bloodstream"],
    velvet: ["satin", "suede"],
    voice: ["tone", "throat"],
    void: ["vacuum", "chasm"],
    whisper: ["mutter", "mumble"],
    whispered: ["muttered", "mumbled"],
    whispering: ["muttering", "mumbling"],
    whispers: ["mutters", "mumbles"],
    wildfire: ["brushfire", "bonfire"],
  };
  // verb-position substitutes — when the cliché word is acting as a VERB ("every heartbeat
  // ECHOES your name", "i LOVE you") the noun table above would break the grammar; these don't.
  globalThis.CLICHE_SWAPS_VERB = {
    love: ["adore", "cherish"],
    echo: ["repeat", "rebound"],
    echoes: ["repeats", "rebounds"],
    echoing: ["repeating", "ringing"],
    whisper: ["mutter", "mumble"],
    whispers: ["mutters", "mumbles"],
    whispered: ["muttered", "mumbled"],
    whispering: ["muttering", "mumbling"],
    kiss: ["peck"],
    flicker: ["sputter", "blink"],
    flickering: ["sputtering", "blinking"],
    surrender: ["yield"],
    scar: ["mark"],
    shimmer: ["glint"],
    glimmer: ["glint"],
  };
})();
