/* _candidates_raw.js — raw human-authored replacement-line candidates with tags.
 * NOT shipped. Fed through analysis/_vet_candidates.js + prosody syllables, then
 * the passers are written into analysis/replacement_catalog.js bucketed by syllable.
 *
 * Tags: ENV, PLACE, OBJECT, DOMESTIC, URBAN, PERSON, BODY (see REPLACEMENT_CATALOG_DESIGN.md)
 * Author rules: ≥1 concrete picture-noun, no cliché/vague/abstract lexicon words,
 * no proper nouns/brands/digits, reads like a real lyric.
 */
module.exports = [
  // ================= ENV (universal default pool) =================
  ['the kettle ticked as it cooled down', ['ENV']],
  ['frost had bitten every pane', ['ENV']],
  ['gulls were arguing over bread', ['ENV']],
  ['the gutter caught the runoff fast', ['ENV']],
  ['a sparrow picked the gravel clean', ['ENV']],
  ['the porch light buzzed and would not quit', ['ENV']],
  ['a magpie clattered on the roof', ['ENV']],
  ['the wind kept slamming the back gate', ['ENV']],
  ['the puddle froze along the kerb', ['ENV']],
  ['steam rolled off the boiling pot', ['ENV']],
  ['the apples bruised against the bowl', ['ENV']],
  ['snow piled up against the shed', ['ENV']],
  ['the awning dripped onto the step', ['ENV']],
  ['a moth kept knocking at the bulb', ['ENV']],
  ['the heater clicked on after dark', ['ENV', 'DOMESTIC']],
  ['rust had eaten through the hinge', ['ENV']],
  ['the kettle screamed and then went quiet', ['ENV']],
  ['a wasp got trapped behind the blind', ['ENV']],
  ['the laundry stiffened on the line', ['ENV']],
  ['hail rattled down the metal roof', ['ENV']],
  ['the fog sat low above the fields', ['ENV', 'PLACE']],
  ['a crow walked slow across the lot', ['ENV']],
  ['the bonfire popped and threw a spark', ['ENV']],
  ['the tide went out and left the weed', ['ENV']],
  ['leaves clogged the drain beside the path', ['ENV', 'PLACE']],
  ['a kettle whistle filled the flat', ['ENV', 'DOMESTIC']],
  ['the fan turned slowly in the heat', ['ENV', 'OBJECT']],
  ['ice cracked along the water trough', ['ENV']],
  ['the chimney smoked against the grey', ['ENV']],
  ['a beetle flipped onto its back', ['ENV']],
  ['the snowmelt ran beneath the porch', ['ENV', 'PLACE']],
  ['a hen kept scratching at the dirt', ['ENV']],
  ['the radiator hissed and knocked', ['ENV', 'DOMESTIC']],
  ['wet leaves stuck flat against the screen', ['ENV']],
  ['the early bus pulled past the stop', ['ENV', 'URBAN']],
  ['the rain kept tapping on the glass', ['ENV']],
  ['wind dragged the leaves across the lot', ['ENV']],
  ['the gravel held the day’s last heat', ['ENV']],
  ['a beetle crossed the warm cement', ['ENV']],
  ['the orchard dropped its fruit unpicked', ['ENV', 'PLACE']],
  ['the cellar smelled of damp and coal', ['ENV', 'PLACE']],
  ['a kettle steamed the window up', ['ENV', 'DOMESTIC']],
  ['the frost had curled the garden leaves', ['ENV', 'PLACE']],
  ['the bathwater had gone stone cold', ['ENV', 'DOMESTIC']],
  ['the swallows lined the power wire', ['ENV', 'URBAN']],
  ['the muddy track had froze to ruts', ['ENV', 'PLACE']],
  ['a single moth burned at the lamp', ['ENV']],
  ['the dripping tap kept up its beat', ['ENV', 'OBJECT', 'DOMESTIC']],
  ['wind worried at the rotten fence', ['ENV', 'PLACE']],
  ['the bread had gone to crust and mould', ['ENV', 'OBJECT']],
  ['the milk had soured in the heat', ['ENV', 'OBJECT', 'DOMESTIC']],
  ['the river carried off the bridge', ['ENV', 'PLACE']],
  ['a damp wind pushed beneath the door', ['ENV', 'DOMESTIC']],

  // ================= PLACE =================
  ['the gate hung open in the wind', ['PLACE', 'ENV']],
  ['the chapel stood with boarded doors', ['PLACE']],
  ['the platform emptied after eight', ['PLACE', 'URBAN']],
  ['the cul-de-sac had one lit house', ['PLACE', 'URBAN']],
  ['the harbour wall was slick with weed', ['PLACE']],
  ['the orchard fence had given way', ['PLACE']],
  ['the bus shelter had cracked its glass', ['PLACE', 'URBAN']],
  ['the quarry filled with rust-brown pools', ['PLACE', 'ENV']],
  ['the hallway smelled of bleach and damp', ['PLACE', 'DOMESTIC']],
  ['the back lot flooded by the bins', ['PLACE', 'URBAN']],
  ['the stairwell echoed with the wind', ['PLACE', 'ENV']],
  ['the allotment shed had blown apart', ['PLACE']],
  ['the church car park was full of weeds', ['PLACE', 'URBAN']],
  ['the field went still before the storm', ['PLACE', 'ENV']],
  ['the towpath narrowed by the lock', ['PLACE']],
  ['the launderette stayed lit till two', ['PLACE', 'URBAN']],
  ['the stadium sat dark and locked', ['PLACE', 'URBAN']],
  ['the marshland swallowed up the path', ['PLACE', 'ENV']],

  // ================= OBJECT =================
  ['the clock kept time it could not keep', ['OBJECT']],
  ['the kettle scaled up white inside', ['OBJECT', 'DOMESTIC']],
  ['the bicycle chain had rusted stiff', ['OBJECT']],
  ['the matchbox rattled nearly bare', ['OBJECT']],
  ['the freezer hummed behind the shop', ['OBJECT', 'URBAN']],
  ['the wristwatch stopped at half past four', ['OBJECT']],
  ['the suitcase sat there packed for weeks', ['OBJECT']],
  ['the doorbell wire had come undone', ['OBJECT', 'DOMESTIC']],
  ['the lighter sparked but would not catch', ['OBJECT']],
  ['the radio hissed between the bands', ['OBJECT', 'DOMESTIC']],
  ['the teapot lid had cracked its knob', ['OBJECT', 'DOMESTIC']],
  ['the ironing board still stood up there', ['OBJECT', 'DOMESTIC']],
  ['the pocket knife had gone to rust', ['OBJECT']],
  ['the wheelbarrow filled up with leaves', ['OBJECT', 'ENV']],
  ['the cracked mug held a cold black tea', ['OBJECT', 'DOMESTIC']],
  ['the typewriter jammed on the same key', ['OBJECT']],

  // ================= DOMESTIC =================
  ['the dishes stacked up by the sink', ['DOMESTIC']],
  ['the kitchen tap had start to drip', ['DOMESTIC', 'OBJECT']],
  ['a coat still hung behind the door', ['DOMESTIC']],
  ['the kettle waited on the hob', ['DOMESTIC', 'OBJECT']],
  ['last evening’s plates still on the side', ['DOMESTIC']],
  ['the fridge door stuck and then gave way', ['DOMESTIC', 'OBJECT']],
  ['the carpet kept the shape of feet', ['DOMESTIC']],
  ['the bedsheets bunched up at the wall', ['DOMESTIC']],
  ['the boots stood dripping by the mat', ['DOMESTIC', 'OBJECT']],
  ['the toaster only browned one side', ['DOMESTIC', 'OBJECT']],
  ['the washing piled up on the chair', ['DOMESTIC']],
  ['the stovetop crusted over black', ['DOMESTIC']],
  ['the curtains never quite would close', ['DOMESTIC']],
  ['the cupboard held one tin of beans', ['DOMESTIC', 'OBJECT']],

  // ================= URBAN =================
  ['the streetlight flickered down the block', ['URBAN', 'ENV']],
  ['a taxi idled at the kerb', ['URBAN']],
  ['the off-licence had pulled its grille', ['URBAN', 'OBJECT']],
  ['the traffic backed up past the bridge', ['URBAN']],
  ['the late train rattled through the cut', ['URBAN']],
  ['the chip shop steamed the window up', ['URBAN', 'ENV']],
  ['a siren faded down the road', ['URBAN']],
  ['the parking meter ate the coin', ['URBAN', 'OBJECT']],
  ['the bin lorry woke the whole street', ['URBAN']],
  ['the underpass dripped on the tiles', ['URBAN', 'ENV']],
  ['the bus was packed and ran ten late', ['URBAN']],
  ['the shutters dropped along the row', ['URBAN', 'OBJECT']],

  // ================= PERSON (HUMAN context only) =================
  ['she left her cup beside the sink', ['PERSON', 'DOMESTIC']],
  ['you didn’t call me back at all', ['PERSON']],
  ['he stacked the chairs and locked the door', ['PERSON', 'DOMESTIC']],
  ['she scraped the frost off both the cars', ['PERSON', 'ENV']],
  ['you left your boots out on the step', ['PERSON', 'OBJECT', 'PLACE']],
  ['he kept the ticket in his coat', ['PERSON', 'OBJECT']],
  ['she counted out the change in coins', ['PERSON', 'OBJECT']],
  ['you spilled the tea across the desk', ['PERSON', 'DOMESTIC']],
  ['he parked the van behind the shop', ['PERSON', 'URBAN']],
  ['she stubbed the cigarette half-smoked', ['PERSON', 'OBJECT']],
  ['you wore that jumper full of holes', ['PERSON', 'OBJECT']],
  ['he taped the boxes shut for good', ['PERSON', 'OBJECT']],
  ['she fed the cat and turned the lock', ['PERSON', 'DOMESTIC']],
  ['you read the paper front to back', ['PERSON', 'OBJECT']],
  ['he hung the washing in the dark', ['PERSON', 'DOMESTIC', 'ENV']],

  // ================= BODY (person or creature) =================
  ['her knuckles cracked against the cold', ['BODY']],
  ['his thumb still smelled of petrol then', ['BODY', 'OBJECT']],
  ['a scar ran white across the wrist', ['BODY']],
  ['her hair was wet against her neck', ['BODY']],
  ['his boots had worn the heels right down', ['BODY', 'OBJECT']],
  ['mud caked thick along the shins', ['BODY', 'ENV']],
  ['her palm had blistered from the spade', ['BODY', 'OBJECT']],
  ['his collar chafed against the sun', ['BODY', 'ENV']],
  ['a splinter sat beneath the nail', ['BODY', 'OBJECT']],
  ['her teeth chattered against the wind', ['BODY', 'ENV']],

  // ================= SHORT (target 5–6 syllables) =================
  ['rain on the tin roof', ['ENV']],
  ['frost on the windscreen', ['ENV']],
  ['steam off the kettle', ['ENV', 'DOMESTIC']],
  ['wind through the gap', ['ENV']],
  ['mud on the doorstep', ['ENV', 'PLACE']],
  ['snow on the back step', ['ENV', 'PLACE']],
  ['birds on the wire', ['ENV', 'URBAN']],
  ['fog down the valley', ['ENV', 'PLACE']],
  ['ice on the bucket', ['ENV', 'OBJECT']],
  ['smoke off the chimney', ['ENV']],
  ['dew on the long grass', ['ENV']],
  ['leaves in the gutter', ['ENV', 'URBAN']],
  ['a moth at the lamp', ['ENV']],
  ['rust on the railing', ['ENV', 'OBJECT']],
  ['a tap left to drip', ['ENV', 'OBJECT', 'DOMESTIC']],
  ['a kettle on the boil', ['DOMESTIC', 'OBJECT']],
  ['boots by the back door', ['DOMESTIC', 'OBJECT']],
  ['plates left in the sink', ['DOMESTIC']],
  ['a coat on the hook', ['DOMESTIC', 'OBJECT']],
  ['a clock with no hands', ['OBJECT']],
  ['a streetlight gone out', ['URBAN', 'ENV']],
  ['gulls over the dock', ['ENV', 'PLACE']],
  ['a gate off its hinge', ['PLACE', 'OBJECT']],
  ['cold tea in the mug', ['OBJECT', 'DOMESTIC']],
  ['her hands on the wheel', ['BODY', 'PERSON', 'OBJECT']],

  // ================= LONG (target 10–12 syllables) =================
  ['the kettle scaled up white inside the spout', ['OBJECT', 'DOMESTIC']],
  ['a magpie clattered on the corrugated roof', ['ENV']],
  ['the gutter overflowed and ran along the kerb', ['ENV', 'URBAN']],
  ['the back gate banged against the post in every gust', ['ENV', 'PLACE']],
  ['the freezer in the corner shop kept up its hum', ['OBJECT', 'URBAN']],
  ['the muddy track had frozen hard to ruts and stone', ['ENV', 'PLACE']],
  ['the kettle whistled twice before it boiled dry', ['OBJECT', 'DOMESTIC']],
  ['the porch bulb buzzed and flickered out and buzzed again', ['ENV', 'OBJECT']],
  ['a wasp got stuck behind the blind and would not leave', ['ENV']],
  ['the laundry stiffened hard as board out on the line', ['ENV', 'DOMESTIC']],
  ['the bin lorry came grinding up the narrow road', ['URBAN']],
  ['the chip shop window steamed and dripped onto the floor', ['URBAN', 'ENV']],
  ['the orchard dropped its fruit and left it on the ground', ['ENV', 'PLACE']],
  ['the cellar smelled of damp and coal and rotting wood', ['ENV', 'PLACE']],
  ['she scraped the frost from both the cars before it warmed', ['PERSON', 'ENV']],
  ['he stacked the plastic chairs and pulled the shutter down', ['PERSON', 'DOMESTIC', 'URBAN']],
  ['the radiator knocked and hissed the whole way through', ['ENV', 'DOMESTIC']],
  ['the cracked mug held a cold black tea since half past eight', ['OBJECT', 'DOMESTIC']],
  ['the launderette stayed lit and humming after two', ['PLACE', 'URBAN']],
  ['a crow walked slow across the cracked car park', ['ENV', 'URBAN']],
  ['the wristwatch on the bedside stopped at half past four', ['OBJECT']],
  ['his thumb still carried petrol from the morning shift', ['BODY', 'OBJECT', 'PERSON']],
  ['the snowmelt ran in channels underneath the porch', ['ENV', 'PLACE']],
  ['the apples in the bowl had bruised and gone to brown', ['ENV', 'OBJECT']],
  ['the bicycle had rusted to the iron rail', ['OBJECT', 'URBAN']],

  // ================= MID FILLERS (7-9, more ENV/PLACE/OBJECT) =================
  ['wet ash sat cold inside the grate', ['ENV', 'DOMESTIC']],
  ['the hedge had grown across the lane', ['PLACE', 'ENV']],
  ['a bucket caught the leaking roof', ['OBJECT', 'DOMESTIC']],
  ['the brambles took the garden wall', ['ENV', 'PLACE']],
  ['the postbox stood knee-deep in weeds', ['URBAN', 'OBJECT']],
  ['a tractor crawled along the ridge', ['PLACE']],
  ['the ferry waited out the fog', ['PLACE', 'ENV']],
  ['the bell tower kept the wrong hour', ['PLACE', 'OBJECT']],
  ['the floorboards swelled up in the damp', ['DOMESTIC', 'ENV']],
  ['the corner shop pulled down its grille', ['URBAN', 'OBJECT']],
  ['a rope swing hung above the creek', ['PLACE', 'OBJECT']],
  ['the chimney pot had cracked in two', ['OBJECT', 'PLACE']],
  ['a heron stood out in the reeds', ['ENV', 'PLACE']],
  ['the pavement buckled by the roots', ['URBAN', 'ENV']],
  ['her coat still dripped onto the tiles', ['BODY', 'PERSON', 'DOMESTIC']],

  // ================= 6-syllable batch =================
  ['the rain on the tin roof', ['ENV']],
  ['cold frost on the windscreen', ['ENV']],
  ['wind down the long valley', ['ENV', 'PLACE']],
  ['ice cracked on the bucket', ['ENV', 'OBJECT']],
  ['a moth at the lamp glass', ['ENV']],
  ['smoke up from the chimney', ['ENV']],
  ['boots dry by the back door', ['DOMESTIC', 'OBJECT']],
  ['a clock with no hands left', ['OBJECT']],
  ['dew thick on the long grass', ['ENV']],
  ['mud caked on the doorstep', ['ENV', 'PLACE']],
  ['rust deep in the railing', ['ENV', 'OBJECT']],
  ['cold tea in the cracked mug', ['OBJECT', 'DOMESTIC']],
  ['a gull on the harbour', ['ENV', 'PLACE']],
  ['her hands flat on the wheel', ['BODY', 'PERSON', 'OBJECT']],
  ['leaves packed in the gutter', ['ENV', 'URBAN']],
  ['a kettle left to boil', ['DOMESTIC', 'OBJECT']],

  // ================= 10-syllable batch =================
  ['the kettle scaled up white along the spout', ['OBJECT', 'DOMESTIC']],
  ['the gutter ran and spilled across the kerb', ['ENV', 'URBAN']],
  ['a heron stood out waiting in the reeds', ['ENV', 'PLACE']],
  ['the wristwatch on the table stopped at four', ['OBJECT', 'DOMESTIC']],
  ['the back gate banged against the rotten post', ['ENV', 'PLACE']],
  ['a moth kept knocking softly at the bulb', ['ENV', 'OBJECT']],
  ['she scraped the windscreen clear before the dawn', ['PERSON', 'ENV']],
  ['the orchard dropped its apples on the grass', ['ENV', 'PLACE']],
  ['the freezer in the corner shop still hummed', ['OBJECT', 'URBAN']],
  ['the muddy track had frozen into ruts', ['ENV', 'PLACE']],

  // ================= 11-syllable batch =================
  ['the gutter overflowed and spilled across the kerb', ['ENV', 'URBAN']],
  ['the back gate banged against the post in the wind', ['ENV', 'PLACE']],
  ['the wristwatch on the table stopped at half past four', ['OBJECT', 'DOMESTIC']],
  ['a heron stood and waited in the frozen reeds', ['ENV', 'PLACE']],
  ['the orchard dropped its apples on the wet black ground', ['ENV', 'PLACE']],
  ['she scraped the frost from off the windscreen at the dawn', ['PERSON', 'ENV']],
  ['the kettle whistled twice and then it boiled away', ['OBJECT', 'DOMESTIC']],
];
